{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Backend CPU ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"user-management\", pod=~\"backend-.*\", container!=\"\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Memeory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"user-management\", pod=~\"backend-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"user-management\", pod=~\"frontend-.*\", container!=\"\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"user-management\", pod=~\"frontend-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"user-management\", app=\"frontend\"}"
    }
   ]
  },
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"user-management\", app=\"backend\"}"
    }
   ]
  }
 ]
}